<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PackageId>AuthEndpoints.OAuth.GitHub</PackageId>
    <Description>GitHub OAuth provider for AuthEndpoints.External.OAuth</Description>
    <Version>3.0.0-preview.4</Version>
    <Authors>madeyoga</Authors>
    <Company>madeyoga</Company>
    <PackageProjectUrl>https://github.com/madeyoga/AuthEndpoints</PackageProjectUrl>
    <RepositoryUrl>https://github.com/madeyoga/AuthEndpoints</RepositoryUrl>
    <PackageTags>auth;endpoints;aspnetcore;oauth;github;identity</PackageTags>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <IsPackable>True</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <None Include="README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <InternalsVisibleTo Include="AuthEndpoints.External.OAuth.Tests" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <ProjectReference Include="..\AuthEndpoints.External.OAuth\AuthEndpoints.External.OAuth.csproj" />
    <PackageReference Include="AspNet.Security.OAuth.GitHub" Version="10.0.0" />
  </ItemGroup>

</Project>
