<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PackageId>AuthEndpoints.External.OAuth</PackageId>
    <Description>Minimal API endpoints for external OAuth authentication (GitHub, Google) with ASP.NET Core Identity</Description>
    <Version>3.0.0-preview.3</Version>
    <Authors>madeyoga</Authors>
    <Company>madeyoga</Company>
    <PackageProjectUrl>https://github.com/madeyoga/AuthEndpoints</PackageProjectUrl>
    <RepositoryUrl>https://github.com/madeyoga/AuthEndpoints</RepositoryUrl>
    <PackageTags>auth;endpoints;aspnetcore;oauth;github;google;identity</PackageTags>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <IsPackable>True</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <None Include="README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <ProjectReference Include="..\AuthEndpoints\AuthEndpoints.csproj" />
    <PackageReference Include="AspNet.Security.OAuth.GitHub" Version="10.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.Google" Version="10.0.2" />
  </ItemGroup>

</Project>
