allowBuilds:
  sharp: true
  '@parcel/watcher': false
  '@tailwindcss/oxide': false
  esbuild: false
  unrs-resolver: false
  vue-demi: false
minimumReleaseAgeExclude:
  - '@nuxt/kit@4.5.2'
  - '@nuxt/nitro-server@4.5.2'
  - '@nuxt/schema@4.5.2'
  - '@nuxt/vite-builder@4.5.2'
  - nuxt@4.5.2
  - '@nuxtjs/mcp-toolkit@0.21.0'
overrides:
  '@babel/core@7': 7.29.7
  '@hono/node-server@1': 1.19.17
  '@tiptap/core': 3.31.3
  '@tiptap/extension-bubble-menu': 3.31.3
  '@tiptap/extension-code': 3.31.3
  '@tiptap/extension-collaboration': 3.31.3
  '@tiptap/extension-drag-handle': 3.31.3
  '@tiptap/extension-drag-handle-vue-3': 3.31.3
  '@tiptap/extension-floating-menu': 3.31.3
  '@tiptap/extension-horizontal-rule': 3.31.3
  '@tiptap/extension-image': 3.31.3
  '@tiptap/extension-mention': 3.31.3
  '@tiptap/extension-node-range': 3.31.3
  '@tiptap/extension-placeholder': 3.31.3
  '@tiptap/markdown': 3.31.3
  '@tiptap/pm': 3.31.3
  '@tiptap/starter-kit': 3.31.3
  '@tiptap/suggestion': 3.31.3
  '@tiptap/vue-3': 3.31.3
  body-parser: 2.3.0
  'brace-expansion@2': 2.1.4
  'brace-expansion@5': 5.0.9
  esbuild: 0.28.2
  'fast-uri@3': 3.1.7
  hono: 4.13.7
  ip-address: 10.7.0
  'js-yaml@4': 4.3.2
  launch-editor: 2.14.1
  'nanoid@3': 3.3.19
  qs: 6.16.0
  sharp: 0.35.4
  shell-quote: 1.10.0
  socket.io-parser: 4.2.7
  svgo: 4.1.0
  tar: 7.5.22
  ws: 8.21.3
